version: "3.8"

services:
  serv:
    build:
      context: ./docker
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - backend

networks:
  backend: